{{- $fullName := include "atlas.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.atlas.service.type }}
  ports:
    - port: {{ .Values.atlas.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "atlas.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
